# Generated by Django 5.0.10 on 2025-01-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detalleventa_creado_en_totalventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalventas',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
