# Generated by Django 5.0.10 on 2025-01-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_finanzas_usuario_salarios'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarios',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.estadoventa'),
        ),
    ]
